name: Linux (Ubuntu 18.04)

on:
  - push
  - pull_request

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bash ci-scripts/linux/5.15.2/install.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        timeout-minutes: 10
        with:
          version: 5.12.5
          target: desktop
          host: linux
          install-deps: true
          modules: 'qtwebengine'

      - name: Building GitQlient
        run: |
          qmake -v
          export QT_PLUGIN_PATH=/home/runner/work/GitQlient/Qt/5.12.5/gcc_64/plugins;
          mkdir build
          qmake GitQlient.pro PREFIX=$(pwd)/AppImage/gitqlient/usr
          make -j 4
          make install
          wget -q -O linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
          chmod +x linuxdeployqt
          ./linuxdeployqt AppImage/gitqlient/usr/share/applications/*.desktop -appimage -no-translations -bundle-non-qt-libs -extra-plugins=iconengines,imageformats
          chmod +x GitQlient-*
          cp GitQlient-* ../
