name: Linux (Ubuntu 18.04)

on:
  - push
  - pull_request

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bash ci-scripts/linux/5.15.2/install.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.2.0
        timeout-minutes: 10
        with:
          version: 5.12.5
          target: desktop
          host: linux
          install-deps: true
          modules: qtwebengine
                
      - name: Building GitQlient
        run: bash ci-scripts/linux/5.15.2/build.sh
