name: Windows

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.env.os }}
    env:
      VERSION: 1.4.2
    strategy:
      matrix:
        env:
          - name: Windows
            os: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        timeout-minutes: 10
        with:
          version: 5.15.2
          target: desktop
          host: windows
          install-deps: true
          modules: 'qtwebengine'
          arch: win64_msvc2019_64

      - name: Install jom
        run: choco install jom -y

      - name: Buil GitQlient
        run: |
          # Setup VS compiler
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
          qmake GitQlient.pro VERSION=${{env.VERSION}}
          jom -j2
